### ISSUE TITLE
About MPLight and Colight code implement problem

### ISSUE THREAD

**Issue by MPHarryZhang** [DaRL-LibSignal/LibSignal#5]
I like this project very much, thanks to the work of all researchers, I have a little question about the code implemented by MPLight.
In the official paper of MPLight, its agent observation is the pressure of the traffic flow at the intersection, which is delta_lane_num_vehicle, and the reward is the pressure of the intersection. However, when our LibSignal reproduces MPLight, the observation setting is lane_count, The documentation states that it should be the number of vehicles driving on each lane. The reward setting is the lane_waiting_count, which should be the number of vehicles waiting on the lane. These seem to be different from the design in the official paper of MPLight. May you tell me what is going on? And the second question is that CoLight code cannot run whether you implement it.

**Comment by ShawLen** [comment]
For the problem of MPLight, we set the obs and reward of most models to be the same to evaluate different models more fairly. Of course, you can also adjust obs and rewards according to your own settings by changing the input parameters of `ob_generator` and `reward_generator` in `agent\mplight.py`.

For the problem of CoLight, we have fixed this error.

**Comment by MPHarryZhang** [comment]
> For the problem of MPLight, we set the obs and reward of most models to be the same to evaluate different models more fairly. Of course, you can also adjust obs and rewards according to your own settings by changing the input parameters of `ob_generator` and `reward_generator` in `agent\mplight.py`.
> 
> For the problem of CoLight, we have fixed this error.

Thank you very much for your answer. Maybe I still have two questions. One is that your obs and reward settings are consistent with most models, but it is different from the original paper design. Will this affect the final effect of the algorithm? If it is affected, can it be considered that it is not completely consistent with the model designed in the original paper? If I want to compare the results with the MPLight in the paper, do I need to modify the relevant file content according to your description? The second is whether the CoLight code you fixed has been made public. Can be for our reference?

**Comment by MPHarryZhang** [comment]
> For the problem of MPLight, we set the obs and reward of most models to be the same to evaluate different models more fairly. Of course, you can also adjust obs and rewards according to your own settings by changing the input parameters of `ob_generator` and `reward_generator` in `agent\mplight.py`.
> 
> For the problem of CoLight, we have fixed this error.

Thank you very much for your answer. Maybe I still have a question. It is that your obs and reward settings are consistent with most models, but it is different from the original paper design. Will this affect the final effect of the algorithm? If it is affected, can it be considered that it is not completely consistent with the model designed in the original paper? If I want to compare the results with the MPLight in the paper, do I need to modify the relevant file content according to your description?

**Comment by MPHarryZhang** [comment]
> We tested the performance of the MPLight following the original paper settings and found it is similar to the model performance under the existing settings. Of course, you can modify the same settings as in the original paper.

Thank you very much for your answer. I hope to continue to communicate with you in the future.
